#!/bin/bash

cat \
subtitles_text/peaky.blinders.s01e01.1080p.bluray.x264-shortbrehd.txt \
subtitles_text/peaky.blinders.s01e02.1080p.bluray.x264-shortbrehd.txt \
subtitles_text/peaky.blinders.s01e03.1080p.bluray.x264-shortbrehd.txt \
subtitles_text/peaky.blinders.s01e04.1080p.bluray.x264-shortbrehd.txt \
subtitles_text/peaky.blinders.s01e05.1080p.bluray.x264-shortbrehd.txt \
subtitles_text/peaky.blinders.s01e06.1080p.bluray.x264-shortbrehd.txt \
> subtitles_text/peaky.blinders.s01

cat \
subtitles_text/peaky.blinders.s02e01.1080p.bluray.x264-shortbrehd.txt \
subtitles_text/peaky.blinders.s02e02.1080p.bluray.x264-shortbrehd.txt \
subtitles_text/peaky.blinders.s02e03.1080p.bluray.x264-shortbrehd.txt \
subtitles_text/peaky.blinders.s02e04.1080p.bluray.x264-shortbrehd.txt \
subtitles_text/peaky.blinders.s02e05.1080p.bluray.x264-shortbrehd.txt \
subtitles_text/peaky.blinders.s02e06.1080p.bluray.x264-shortbrehd.txt \
> subtitles_text/peaky.blinders.s02

cat \
subtitles_text/Peaky.Blinders.S03E01.1080p.BluRay.x264-SHORTBREHD.txt \
subtitles_text/Peaky.Blinders.S03E02.1080p.BluRay.x264-SHORTBREHD.txt \
subtitles_text/Peaky.Blinders.S03E03.1080p.BluRay.x264-SHORTBREHD.txt \
subtitles_text/Peaky.Blinders.S03E04.1080p.BluRay.x264-SHORTBREHD.txt \
subtitles_text/Peaky.Blinders.S03E05.1080p.BluRay.x264-SHORTBREHD.txt \
subtitles_text/Peaky.Blinders.S03E06.1080p.BluRay.x264-SHORTBREHD.txt \
> subtitles_text/peaky.blinders.s03

cat \
subtitles_text/Peaky.Blinders.S04E01.720p.BluRay.x264-SHORTBREHD.txt \
subtitles_text/Peaky.Blinders.S04E02.720p.BluRay.x264-SHORTBREHD.txt \
subtitles_text/Peaky.Blinders.S04E03.720p.BluRay.x264-SHORTBREHD.txt \
subtitles_text/Peaky.Blinders.S04E04.720p.BluRay.x264-SHORTBREHD.txt \
subtitles_text/Peaky.Blinders.S04E05.720p.BluRay.x264-SHORTBREHD.txt \
subtitles_text/Peaky.Blinders.S04E06.720p.BluRay.x264-SHORTBREHD.txt \
> subtitles_text/peaky.blinders.s04

cat \
subtitles_text/Peaky.Blinders.S05E01.1080p.BluRay.x264-SHORTBREHD.txt \
subtitles_text/Peaky.Blinders.S05E02.1080p.BluRay.x264-SHORTBREHD.txt \
subtitles_text/Peaky.Blinders.S05E03.1080p.BluRay.x264-SHORTBREHD.txt \
subtitles_text/Peaky.Blinders.S05E04.1080p.BluRay.x264-SHORTBREHD.txt \
subtitles_text/Peaky.Blinders.S05E05.1080p.BluRay.x264-SHORTBREHD.txt \
subtitles_text/Peaky.Blinders.S05E06.1080p.BluRay.x264-SHORTBREHD.txt \
> subtitles_text/peaky.blinders.s05
